server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j

  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    #default-encoding: UTF-8
    settings.template_update_delay: 0
    settings.number_format: 0.##########
    settings.datetime_format: yyyy-MM-dd HH:mm:ss
    settings.classic_compatible: true
    settings.template_exception_handler: ignore
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.wyb.shiro.dao.model

#mapper:
#  mappers: com.wyb.shiro.dao.BaseMapper
#  not-empty: false
#  identity: MYSQL
#  style: camelhump

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#自定义日志
logging:
  level:
    root: info
#  config: classpath:log4j2/log4j2.xml


wx:
  appId: wx555e719fb5428862
  appSecret: f3aafcdeb913a5990893854f2938f204
  token: asfasdjasbdgjayfguajsvdjasbdjaygdas
  aesKey:
#
#wx:
#  appId: wxfb63ccee3cabe09f
#  appSecret: 1c26530b533a34b767f1fbb2ae3bb2ae
#  token: asfasdjasbdgjayfguajsvdjasbdjaygdas
#  aesKey:

